import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { aiService } from '@/lib/aiService';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const opp = await db.getOpportunityById(id);

    if (!opp) {
      return NextResponse.json({ success: false, error: 'Opportunity not found' }, { status: 404 });
    }

    const prdContent = await aiService.generatePRD({
      opportunityTitle: opp.title,
      productName: opp.product?.name || 'Core Product',
      ticketCount: opp.total_tickets || 4,
      customerCount: opp.affected_customers_count || 3,
      affectedArr: Number(opp.affected_arr) || 1200000
    });

    const updatedOpp = await db.updateOpportunityPRD(id, prdContent);

    return NextResponse.json({
      success: true,
      message: 'PRD autonomously generated by Intelligence Engine',
      data: updatedOpp
    });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
